from .download import NODE_CLASS_MAPPINGS as TD_NCM,NODE_DISPLAY_NAME_MAPPINGS as TD_NDCM
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(TD_NCM)
NODE_DISPLAY_NAME_MAPPINGS.update(TD_NDCM)
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']